version: '3.5'

volumes:
  elastic-data:
    {}

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    network_mode: host
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data/
    restart: always

  elastic_search_agent:
    build:
      context: agent
      dockerfile: Dockerfile
    container_name: elastic_search_agent
    network_mode: host
    environment:
      - ELASTIC_AGENT_HOST
      - ELASTIC_AGENT_PORT
      - ELASTIC_SEARCH_HOST
      - ELASTIC_SEARCH_PORT
    depends_on:
      - elasticsearch
    restart: always

  ckan:
    build:
      context: ckan
      dockerfile: Dockerfile
      network: host
      args:
        - CKAN_DB_URL
        - CKAN_URL
        - DOI_PREFIX
        - ELASTIC_AGENT_URL
        - HYDRA_PUBLIC_URL
        - HYDRA_ADMIN_URL
        - OAUTH2_CLIENT_SECRET
        - IDENTITY_SERVICE_URL
    container_name: ckan
    network_mode: host
    depends_on:
      - solr
    restart: always

  solr:
    build:
      context: solr
      dockerfile: Dockerfile
    container_name: solr
    network_mode: host
    restart: always
