version: '3.5'

networks:
  ckan-net:
    name: ckan-net
  elastic-net:
    name: elastic-net

volumes:
  elastic-data:

services:
  ckan:
    container_name: ckan
    build:
      context: ckan
      args:
        - SERVER_ENV
        - CKAN_DB_URL
        - CKAN_URL
        - DOI_PREFIX
        - HYDRA_PUBLIC_URL
        - HYDRA_ADMIN_URL
        - OAUTH2_CLIENT_SECRET
        - IDENTITY_SERVICE_URL
        - ELASTIC_AGENT_URL=http://es-agent:9210
        - SOLR_URL=http://solr:8983/solr
        - REDIS_URL=http://redis:6379/0
        - RABBITMQ_HOST=rabbitmq
    networks:
      - ckan-net
      - elastic-net
    ports:
      - "5000:5000"
    depends_on:
      - solr
      - redis
    restart: always

  es-agent:
    container_name: es-agent
    build:
      context: es_agent
    networks:
      - elastic-net
    ports:
      - "9210:9210"
    environment:
      - ELASTIC_AGENT_HOST=localhost
      - ELASTIC_AGENT_PORT=9210
      - ELASTIC_SEARCH_HOST=elasticsearch
      - ELASTIC_SEARCH_PORT=9200
    depends_on:
      - elasticsearch
    restart: always

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    networks:
      - elastic-net
    ports:
      - "9200:9200"
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data/
    restart: always

  solr:
    container_name: solr
    build:
      context: solr
    networks:
      - ckan-net
    restart: always

  redis:
    container_name: redis
    image: redis:5
    networks:
      - ckan-net
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3
    networks:
      - ckan-net
    restart: always
