version: '3.5'

networks:
  elastic-net:

volumes:
  elastic-data:

services:
  ckan:
    build:
      context: ckan
      dockerfile: Dockerfile
      network: host
      args:
        - CKAN_DB_URL
        - CKAN_URL
        - DOI_PREFIX
        - HYDRA_PUBLIC_URL
        - HYDRA_ADMIN_URL
        - OAUTH2_CLIENT_SECRET
        - IDENTITY_SERVICE_URL
        - ELASTIC_AGENT_URL=http://localhost:9210
    container_name: ckan
    network_mode: host
    depends_on:
      - solr
      - redis
    restart: always

  elastic_search_agent:
    build:
      context: agent
      dockerfile: Dockerfile
    container_name: elastic_search_agent
    networks:
      - elastic-net
    ports:
      - "9210:9210"
    environment:
      - ELASTIC_AGENT_HOST=localhost
      - ELASTIC_AGENT_PORT=9210
      - ELASTIC_SEARCH_HOST=elasticsearch
      - ELASTIC_SEARCH_PORT=9200
    depends_on:
      - elasticsearch
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    container_name: elasticsearch
    networks:
      - elastic-net
    environment:
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic-data:/usr/share/elasticsearch/data/
    restart: always

  solr:
    build:
      context: solr
      dockerfile: Dockerfile
    container_name: solr
    network_mode: host
    restart: always

  redis:
    image: redis
    container_name: redis
    network_mode: host
    restart: always
