version: '2'
services:
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
        container_name: elasticsearch
        ports:
            - "9200:9200"
        environment:
            - cluster.name=docker-cluster

            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 1g

    elastic_search_agent:
        build:
            context: ./agent_docker
            dockerfile: Dockerfile

        container_name: search_agent

        ports:
            - "9210:9210"
        
        depends_on:
            - elastic

    pycsw:
        build:
            context: ./pycsw_docker
            dockerfile: Dockerfile

        container_name: pycsw

        ports:
            - "8000:8000"

        depends_on:
            - elastic_search_agent
